name: Deployment
on:
  push:
    tags:
      - 'v*'
jobs:
  create_release:
    runs-on: ubuntu-20.04
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Fetch tag git metadata
        run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
      - name: Check for .NET 6 preinstalled
        id: dotnet_check
        run: |
          compgen -G "~/.dotnet/sdk/6.0.*" \
          && echo "::set-output name=has_6_0::true" || \
          compgen -G "/usr/local/dotnet/sdk/6.0.*" \
          && echo "::set-output name=has_6_0::true" || \
          compgen -G "/usr/share/dotnet/sdk/6.0.*" \
          && echo "::set-output name=has_6_0::true" || true
      - uses: actions/setup-dotnet@v1.9.1
        if: ${{ steps.dotnet_check.outputs.has_6_0 != 'true' }}
        with:
          dotnet-version: 6.0.x
      - name: NuGet Auth
        uses: StirlingLabs/GithubNugetAuthAction@main
        with:
          token: ${{secrets.DAEMON_NUGET}}
      - name: Build
        run: dotnet build StirlingLabs.Collections.Net.sln -c Release
      - name: Test
        run: dotnet test StirlingLabs.Collections.Net.sln --no-build -c Release --logger GitHubActions
      - name: Push NuPkg
        run: dotnet nuget push artifacts/*.nupkg -k ${{github.token}} -s https://nuget.pkg.github.com/${{github.repository_owner}}/index.json -n 1
      - name: Save coverage to storage branch
        uses: StirlingLabs/BranchStorageAction@v21.07.3
        with:
          comment: |
            Coverage for ${{github.ref}}
            Action: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
            Commit: https://github.com/${{github.repository}}/commit/${{github.sha}}
          storage-branch: coverage
          src: coverage
          dst: coverage
          prune: true
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.12
        with:
          name: StirlingLabs.Utilities.Collections
          files: |
            artifacts/*.*
        env:
          GITHUB_TOKEN: ${{github.token}}